<?php

namespace SiteBundle\Repository;

/**
 * GuitarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuitarRepository extends \Doctrine\ORM\EntityRepository
{
}
