<?php

namespace SiteBundle\Repository;

/**
 * Subtype1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subtype1Repository extends \Doctrine\ORM\EntityRepository
{
}
